version: "3.8"
services:
  webapp:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    volumes:
      - D:/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: spring_DB
      MYSQL_USER: mehdi
      MYSQL_PASSWORD: mehdi
      MYSQL_ROOT_PASSWORD: mehdi
volumes:
  db:
