# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Dev Ops Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
          java-version: '11'
          distribution: 'adopt'

    - name: Build with Maven
      run: mvn --batch-mode -DskipTests package --file pom.xml

    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
          name: github-action-artifact
          path: .mvn/wrapper/*.jar

  database_unit_tests:
    name: Test Database
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test with Maven
        run: mvn --batch-mode -Dtest=DataBaseTests -DfailIfNoTests=false test

  unit_tests:
    name: Tests Unitaire
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test with Maven
        run: mvn --batch-mode -Dtest=ProduitControllerUnitTest -DfailIfNoTests=false test

  integration_tests:
    name: Tests d'Integration
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test with Maven
        run: mvn --batch-mode -Dtest=ProduitControllerIntegrationTest -DfailIfNoTests=false test

  performance_tests:
    name: Tests de performance
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test with Maven
        run: mvn --batch-mode -Dtest=ProduitControllerIntegrationTest -DfailIfNoTests=false test
  #k6_load_test:
  #  needs: build
   # name: k6 Load Test
    #runs-on: ubuntu-latest
    #steps:
     # - name: Checkout
      #  uses: actions/checkout@v1

      #- name: Run local k6 test
       # uses: grafana/k6-action@v0.2.0
        #with:
         # filename: k6/script.js
  deploy:
    needs: [database_unit_tests, unit_tests, integration_tests, performance_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build with Maven
        run: mvn clean install

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: mehdii909/spring-boot-image
          tags: latest
          registry: Docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    
 
