# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Dev Ops Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
          java-version: '11'
          distribution: 'adopt'

    - name: Build with Maven
      run: mvn --batch-mode -DskipTests package --file pom.xml

    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
          name: github-action-artifact
          path: .mvn/wrapper/*.jar

  database_unit_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test with Maven
        run: mvn --batch-mode -Dtest=DataBaseTests -DfailIfNoTests=false test

  unit_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test with Maven
        run: mvn --batch-mode -Dtest=ProduitControllerUnitTest -DfailIfNoTests=false test

  integration_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test with Maven
        run: mvn --batch-mode -Dtest=ProduitControllerIntegrationTest -DfailIfNoTests=false test

  k6_load_test:
    needs: build
    name: k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: test.js
          
    
 
